import React from "react";
import LegalPage from "./LegalPage";

export default function TermsOfUse() {
  return (
    <LegalPage title="Terms of Use">
      <h1 className="text-3xl sm:text-5xl font-extrabold text-[#19CC7E] leading-tight mb-4">
        TERMS OF USE &amp; USER AGREEMENT
      </h1>
      <p className="text-sm text-[#1A1A1A]/70 mb-2"><strong>Effective Date:</strong> June 8, 2026</p>
      <p className="text-sm text-[#1A1A1A]/70 mb-2"><strong>Version:</strong> 1.0</p>
      <p className="text-sm text-[#1A1A1A]/70 mb-10"><strong>Document Status:</strong> Electronic Record under the Information Technology Act, 2000</p>

      <p className="mb-4 leading-relaxed">
        This User Agreement (the <strong>"Agreement"</strong>) is a legally binding contract made between you (the <strong>"User"</strong> or <strong>"You"</strong>) and <strong>Finaptis Wealthtech Private Limited</strong> (hereinafter referred to as <strong>"Finaptis"</strong>, <strong>"Company"</strong>, <strong>"Us"</strong> or <strong>"We"</strong>), a private limited company having its registered office at <em>No 13/1 Standage Road, 2nd Floor, Frazer Town, Bangalore North, Karnataka, India, 560005</em> (<strong>CIN: U66190KA2024PTC195442</strong>).
      </p>
      <p className="mb-4 leading-relaxed">
        The User and Finaptis shall be collectively referred to as the <strong>"Parties"</strong> and individually as a <strong>"Party"</strong>. This Platform operates under the domain <strong>myanchorscore.com</strong> (the <strong>"Platform"</strong>).
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">1. Acceptance of Terms &amp; The Anchor Score Methodology</h3>
      <p className="mb-4 leading-relaxed">
        By creating an account, accessing, or browsing myanchorscore.com, you explicitly agree to these Terms of Use and our Privacy Policy.
      </p>
      <ul className="list-disc pl-6 space-y-3 mb-4 leading-relaxed">
        <li><strong>Proprietary Framework:</strong> You acknowledge that the <strong>"Anchor Score"</strong> displayed on the Platform is a proprietary financial health tracking and evaluation methodology developed exclusively by Finaptis.</li>
        <li><strong>Not an Official Credit Score:</strong> The Anchor Score is <strong>not</strong> a credit score generated by RBI-approved Credit Information Companies (such as CIBIL, Experian, Equifax, or CRIF High Mark). It is an analytical metric designed to give you a conceptual overview of your financial health based on the data points you input or link on the platform.</li>
      </ul>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">2. Services Offered</h3>
      <p className="mb-4 leading-relaxed">
        Finaptis provides a digital wealthtech platform under the brand <strong>myanchorscore.com</strong> that facilitates:
      </p>
      <ul className="list-disc pl-6 space-y-3 mb-4 leading-relaxed">
        <li>The calculation, tracking, and visualization of your financial health via our proprietary Anchor Score methodology.</li>
        <li>The distribution, tracking, and execution of investment products, specifically regular plan mutual funds.</li>
      </ul>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">3. Eligibility &amp; Account Integrity</h3>
      <p className="mb-4 leading-relaxed">
        To use our Services, you must be a tax resident of India, at least 18 years old, and legally capable of entering into a contract under the Indian Contract Act, 1872. You are responsible for keeping your login credentials confidential and ensuring all financial and identity data you input is accurate and current.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">4. AMFI Registration &amp; Mutual Fund Distribution Disclosures</h3>
      <ul className="list-disc pl-6 space-y-3 mb-4 leading-relaxed">
        <li><strong>Corporate Distribution Status:</strong> Finaptis Wealthtech Private Limited is registered with the Association of Mutual Funds in India (AMFI) as a Corporate Mutual Fund Distributor holding a valid <strong>AMFI Registration Number (ARN) 318892</strong>.</li>
        <li><strong>Execution-Only Platform (Non-Advisory):</strong> We operate strictly as a distributor of mutual fund products, <strong>not as a SEBI-registered Investment Adviser</strong>. The Anchor Score, financial metrics, and insights provided on the Platform are for informational and educational purposes. They do not constitute formal investment, legal, tax, or financial planning advice.</li>
        <li><strong>Regular Plans &amp; Commission:</strong> The Platform offers <strong>Regular Plan</strong> mutual fund schemes. Regular Plans involve the payment of distribution commissions by Asset Management Companies (AMCs) to Finaptis. As per the AMFI Code of Conduct, our complete commission structure across various fund houses is transparently disclosed for your review on our dedicated corporate disclosures page linkable directly from the main footer of the Platform.</li>
      </ul>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">5. Onboarding &amp; Compliance Partners</h3>
      <p className="mb-4 leading-relaxed">
        To securely process identity verifications and complete mandatory Know Your Customer (KYC) regulatory protocols for mutual fund investing, our Platform integrates with authorized technology processors. <strong>You explicitly authorize us to securely process your registration data (PAN, bank parameters, and identity proofs) through our partners:</strong>
      </p>
      <ul className="list-disc pl-6 space-y-3 mb-4 leading-relaxed">
        <li><strong>Decentro Tech Private Limited</strong></li>
        <li><strong>Cybrilla Technologies Private Limited</strong></li>
      </ul>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">6. Intellectual Property Rights</h3>
      <p className="mb-4 leading-relaxed">
        The Platform, its source code, user interfaces, logos, graphics, and the algorithmic models/math governing the <strong>Anchor Score methodology</strong> are the exclusive intellectual property of Finaptis Wealthtech Private Limited. You are granted a limited, revocable, non-transferable license to utilize the platform for personal, non-commercial financial tracking.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">7. Prohibited Conduct</h3>
      <p className="mb-4 leading-relaxed">
        Users agree not to use the Platform for unauthorized or illegal financial activity, impersonate any individual during KYC, attempt to reverse-engineer our score calculations, or deploy automated bots/scrapers to pull financial data from myanchorscore.com.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">8. Financial Disclaimer &amp; Market Risks</h3>
      <p className="mb-4 leading-relaxed">
        All calculations, analytics, and scores provided by our methodology are tools for self-evaluation. <strong>Mutual fund investments are subject to market risks.</strong> You are solely responsible for reading the Scheme Information Documents (SIDs), Key Information Memorandums (KIMs), and tracking fund parameters prior to investing. Finaptis does not guarantee investment returns or performance of any mutual fund scheme.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">9. Limitation of Liability &amp; Indemnity</h3>
      <p className="mb-4 leading-relaxed">
        To the maximum extent permitted by applicable Indian law, Finaptis, its directors, employees, or tech partners (including Decentro and Cybrilla) shall not be liable for any direct or indirect financial losses, market losses, or damages resulting from your reliance on the Anchor Score or your use of the Platform. You agree to indemnify and hold Finaptis harmless against any claims arising out of your violation of these terms.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">10. Governing Law &amp; Jurisdiction</h3>
      <p className="mb-4 leading-relaxed">
        This Agreement shall be governed by and construed in accordance with the laws of India. Any legal disputes or claims arising out of the use of the Platform shall be subject to the exclusive jurisdiction of the competent courts located in <strong>Bangalore, Karnataka, India</strong>.
      </p>

      <h3 className="text-xl sm:text-2xl font-bold text-[#1A1A1A] mt-10 mb-3">11. Grievance Officer &amp; Support Contacts</h3>
      <p className="mb-4 leading-relaxed">
        In compliance with the Information Technology Act, 2000 and data regulations, any structural complaints, platform discrepancies, or privacy questions should be directed to our Grievance Officer:
      </p>
      <ul className="list-disc pl-6 space-y-3 mb-4 leading-relaxed">
        <li><strong>Name:</strong> Arun Kumar</li>
        <li><strong>Designation:</strong> Grievance Officer</li>
        <li><strong>Email Address:</strong> admin@myanchorscore.com</li>
        <li><strong>Postal Address:</strong> Finaptis Wealthtech Private Limited, No 13/1 Standage Road, 2nd Floor, Frazer Town, Bangalore North, Karnataka, India, 560005.</li>
      </ul>
    </LegalPage>
  );
}
